### ISSUE TITLE
collection in post appears the item repeat 

### ISSUE THREAD

**Issue by eteled126** [hyunsupul/aesop-core#357] opened 2019-03-13 12:16 UTC
Hello, I found a problem in use: insert "collection" in post, enable "load more",

After publishing, click the "load more" button and you will find that  the last item before loading is the same as the first item after loading, that is, there is one item that appears twice!

<img src="https://s2.ax1x.com/2019/03/13/Akabf1.jpg" alt="Akabf1.jpg" border="0" />

**Comment by HeyTC-au** [comment] 2019-04-27 23:21
Experiencing the same Issue. Getting duplicate posts in a collection when Load More is clicked. 

Category collection set to either 
- 2 images / 2 columns
- 3 images / 3 columns

It seems that the initially loaded posts get duplicated when the first **_Load more_** get clicked. Subsequent clicks of **_Load More_** does not further duplicate posts.  It is not related to using multiple categories

![category-post-duplication](https://user-images.githubusercontent.com/47260288/56856062-4713c680-6996-11e9-9b69-604208fdec2f.png)
.

**Comment by hyunsupul** [comment] 2019-05-17 20:48
Hi I think the issue is fixed with the latest code (2.0.8.5)

**Closed by hyunsupul** 2019-05-17 20:48 UTC
