### ISSUE TITLE
Drafts are also displayed in the collection

### ISSUE THREAD

**Issue by eteled126** [hyunsupul/aesop-core#361] opened 2019-03-19 06:22 UTC
New post, add collection component, select a category .publication.
If there are unpublished articles (drafts) under the same category, they also will be displayed to the public in the list.

**Comment by hyunsupul** [comment] 2019-03-19 12:31
Thank you for your report but I could not reproduce the problem when I tried this.

**Comment by hyunsupul** [comment] 2019-05-17 20:48
Hi I think the issue is fixed with the latest code (2.0.8.5)

**Closed by hyunsupul** 2019-05-17 20:48 UTC
